### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by phastekk** [ianmarmour/nvidia-clerk#113] opened 2020-09-25 20:46 UTC
Had this pop up while running

"https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481700": readAn existing connection was forcibly closed by the remote host.

**Comment by ianmarmour** [comment] 2020-09-25 21:43
Closing this in favor of #116 see this issue for relevant updates and information as well as the cause.

**Closed as completed by ianmarmour** 2020-09-25 21:43 UTC
Labels: bug, duplicate
