### ISSUE TITLE
Feature request: SMS Alert when code stops running

### ISSUE THREAD

**Issue by LN-MAG** [ianmarmour/nvidia-clerk#78] opened 2020-09-24 09:47 UTC
Would be nice to receive an SMS alert when the code runs into errors that causes it to stop running. Otherwise I have to regularly check to see that it's running as it should. Don't have the knowledge to implement this myself.

Since the last hour I keep getting this error when the region is set to GBR: panic: runtime error: index out of range [0] with length 0. The error occurs occassionally, about every 5 minutes or so.

**Comment by ianmarmour** [comment] 2020-09-24 19:09
I solved the root cause of this exception, as far as I can tell all exception paths should be handled now (short of segfaults, which I don't know if I can throw during anyway). I'm going to close this in favor of cleanly handling all errors, as a side note notifications get sent before browser opening now so even in the case of a failure there you should still be notified (please see latest release for this change)

**Closed as completed by ianmarmour** 2020-09-24 19:09 UTC
Labels: enhancement, help wanted
