### ISSUE TITLE
ERROR: context deadline exceeded

### ISSUE THREAD

**Issue by ghost** [ianmarmour/nvidia-clerk#150] opened 2020-09-29 12:08 UTC
**Describe the bug**

While testing for the RTX 2080 TI or any other card, I get the follwoing error:
`2020/09/29 14:01:59 Get "https://api-prod.nvidia.com/direct-sales-shop/DR/products/de_de/EUR/5394901600": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

OS: Windows
Command: nvidia-clern-windows.exe -telegram -region=DEU -model2080TI

**Comment by BROKENMIND617** [comment] 2020-09-29 12:17
API is down. Consensus is that it needs to be fixed on Nvidia end. They may be working on the API. Apparently it has gone down before. Its been down pretty much consistently since last night.

**Comment by ghost** [comment] 2020-09-29 12:21
Checked the partners API:
https://api.nvidia.partners/edge/product/search?page=1&limit=9&locale=en-us&category=GPU&gpu=RTX%203090&manufacturer=NVIDIA&manufacturer_filter=NVIDIA~1,ASUS~1,EVGA~3,GIGABYTE~2,MSI~1,PNY~0,ZOTAC~0

Its working fine...

Maybe they deactivated the API for the direct-sales, because of thier bot issue during the RTX 30xx release.

**Comment by BROKENMIND617** [comment] 2020-09-29 12:27
The URL looks different from the one I was checking last night. Is the AIB API different for Nvidia FE, or are they one in the same?  This one is much longer. Also the 2060 doesn't refresh with add to cart on phone .

**Comment by WeetA34** [comment] 2020-09-29 13:08
The api.nvidia.partners/edge/product/search?... query can report a prdStatus equals to check_availability instead of upcoming.
When it happens, a call to api-prod.nvidia.com/direct-sales-shop/... seems mandatory to get a relevant result.
If you test with a 2080 SUPER, prdStatus returns buy_now then a call to api-prod.nvidia.com is automaticaly done.

**Comment by HelloThisIsFlo** [comment] 2020-09-29 14:07
I think it's most likely a temporary issue, as mentioned by @BROKENMIND617, and not a deactivation.
The reason I'm thinking this is because even on the official website it seems they have the same problem :) 
<img width="995" alt="nvidiaLoading" src="https://user-images.githubusercontent.com/10831649/94569275-71417600-0265-11eb-846c-2c4812b76732.png">

**Comment by WeetA34** [comment] 2020-09-29 14:20
exactly. Like this WE

**Comment by redstone2019** [comment] 2020-09-29 16:06
NVIDIA issues not us

**Closed as completed** 2020-09-29 16:06 UTC
Labels: bug, duplicate

**Comment by HelloThisIsFlo** [comment] 2020-09-29 16:19
Hey @redstone2019,
If you want to avoid people posting duplicate every time they see this error, maybe you could keep the issue open until nvidia fixes the problem 🙂 Just an idea to minimize unintentional spam 😌

**Comment by BROKENMIND617** [comment] 2020-09-29 16:37
You can also search closed Issues.

**Comment by HelloThisIsFlo** [comment] 2020-09-29 16:47
@BROKENMIND617 
For sure, one could, I would... I just have a hunch that most people won't 😊

Most people using this bot are not professional devs, I'd assume when they see the issue isn't listed they automatically think it'd be a good idea to create a new one. Hence, all the duplicates about this one issue 🙂

**Comment by redstone2019** [comment] 2020-09-29 19:05
We already have tried leaving them open but people still posted anyway so we close issues that don't need development from us.
