### ISSUE TITLE
Client Timedout exceeded while awaiting headers error

### ISSUE THREAD

**Issue by Hosua101** [ianmarmour/nvidia-clerk#116] opened 2020-09-25 21:14 UTC
![image](https://user-images.githubusercontent.com/18233684/94316561-303a2080-ff4a-11ea-8f29-62980e9eb445.png)

**Comment by Sadge-spec** [comment] 2020-09-25 21:16
It looks like they changed the API again. They did this before they released another set of batch two days ago.

**Comment by gamingarena23** [comment] 2020-09-25 21:16
Yeah same problem:
""https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481600": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

**Comment by CPYY** [comment] 2020-09-25 21:18
Same issue

**Comment by m9x3mos** [comment] 2020-09-25 21:22
Yeah I think even their site isn't updated fully. The option for out of stock or buy is missing from the 3090 page and the 2060 buy now button doesn't show up and just has a spinner.

**Comment by ianmarmour** [comment] 2020-09-25 21:40
I don't think they changed their API most likely just the website is down from traffic (not positive about that but it's possible) we're just getting client timeouts which means increased latency (meaning nvidia server issues) I'll track this to see if the API changes again though it's possible. This project is open source so if they're monitoring it they could be trying to patch things as I use them.... "shrug"

**Comment by zulrang** [comment] 2020-09-25 21:52
Need to increase the timeout:

```
var timeTillContextDeadline = time.Now().Add(3 * time.Second)

ctx, ctxCancelFunc = context.WithDeadline(context.Background(), timeTillContextDeadline)
```

**Comment by ibot4fun** [comment] 2020-09-25 22:01
\nvidia-clerk-3.6>nvidia-clerk-windows.exe -sms
2020/09/25 17:00:51 invalid character '<' looking for beginning of value
2020/09/25 17:00:51 Error getting session token from NVIDIA retrying...

**Comment by ibot4fun** [comment] 2020-09-25 22:06
From observation. the in stock status is taking 10-15 seconds after the page loads to visually appear. I don't know if this is caused by a delay to present stock status to the user or if it's just delay/lag.

**Comment by ianmarmour** [comment] 2020-09-25 22:08
https://shop.nvidia.com is down for maintenance right now.

We get the session token from this API at the start of the application therefor monitoring is broken right now (checkout probably is to)

That being said we could move the monitoring code outside of this loop to monitor even when the store is down.

**Comment by m9x3mos** [comment] 2020-09-25 22:17
> From observation. the in stock status is taking 10-15 seconds after the page loads to visually appear. I don't know if this is caused by a delay to present stock status to the user or if it's just delay/lag.

I think this might be some form of rate limiting. I saw this on my computer as well. When I attempt to load it on my cell phone (not on wifi) it loads much faster. Just my 2 cents (not jayz).

**Comment by ianmarmour** [comment] 2020-09-25 22:32
It's not rate limiting as far as I can tell, I haven't hit the site at all today and now if I attempt to go to the shop I can't get a valid session, and on-top of that I can't can't hit the direct session token generation endpoint as well. Either their changing their session logic or their API is falling over not sure which yet.

**Comment by ianmarmour** [comment] 2020-09-25 22:33
For those of you that already have a valid session maybe the API will continue to work (generally for up to 24 hours after you token is generated) but I doubt that.

**Comment by Fly1ngSquid** [comment] 2020-09-25 22:35
Worth noting that there's definitely something changing on Nvidia's end.
[Attempting to access store support from this page](https://www.nvidia.com/en-us/support/consumer/) leads to an under maintenance page.

I have an NV link in my cart from previously in the day that I cannot remove, or checkout either.

**Comment by ianmarmour** [comment] 2020-09-25 22:41
They're probably doing a deployment of some kind, not sure if it will impact clerk yet, I'll keep an eye out as the changes roll out we make use of the API heavily right now so who knows what it's going to do.

**Comment by HiramIII** [comment] 2020-09-26 00:23
@ianmarmour Is it fine to use a previous release if a newer one isn't working? The v3.7.2 is giving me the runtime unknown error again, while v3.6 stills works it just gives this error: 
2020/09/25 17:20:15 invalid character '<' looking for beginning of value
2020/09/25 17:20:15 Error getting session token from NVIDIA retrying...

**Comment by POD-io** [comment] 2020-09-26 06:16
Still an issue for others? As of 2AM EST I am getting the Client.Timeout exceeded while awaiting headers

**Comment by EtienneK** [comment] 2020-09-26 07:03
Yes, still experiencing it using the NL store.

**Comment by ianmarmour** [comment] 2020-09-26 08:19
See discord, nvidia is still down

**Comment by CPYY** [comment] 2020-09-26 08:57
> See discord, nvidia is still down

How come nvidia snatcher is working fine if nvidia is down tho? Just curious.
![Screenshot_1](https://user-images.githubusercontent.com/71854602/94336934-c0826f00-fff7-11ea-8216-607636d92cfe.png)

**Comment by mickyg33** [comment] 2020-09-26 16:15
Looks like it's just come back

**Comment by warrengc3** [comment] 2020-09-26 17:06
yup at 12:10 EDT

**Comment by warrengc3** [comment] 2020-09-26 17:07
![Screen Shot 2020-09-26 at 1 07 23 PM](https://user-images.githubusercontent.com/20330266/94346249-49e67100-fff9-11ea-8acd-fe824c8934d7.png)

**Comment by warrengc3** [comment] 2020-09-26 17:09
![Screen Shot 2020-09-26 at 1 08 42 PM](https://user-images.githubusercontent.com/20330266/94346271-73070180-fff9-11ea-93e7-70320f53367e.png)

**Comment by redstone2019** [comment] 2020-09-26 18:49
This issue has been fixed by nvidia

**Closed as completed** 2020-09-26 21:39 UTC
Labels: bug, wontfix
